# The program should have an athlete class
# The athlete has the following attributes: athlete id (class variable whose value is generated by the program), first_name, last_name, medals_earned, and total_earned_amount
#The athlete constructor receives the two strings for the contestant first and last names as parameters and populates those attributes
# It also generates the id value and stores it to the attribute
# The medals_earned attribute will be an empty list. The total_earned_amount attribute should be initialized to 0
# This class should also have a method called get_fullname that returns the first and last name attributes concatenated with a space separating the two, and the first letter of the first and last capitalized

class Athlete:
    athlete_id = 0

    def __init__(self, first_name, last_name):
        Athlete.athlete_id += 1
        self.athlete_id = Athlete.athlete_id
        self.first_name = first_name
        self.last_name = last_name
        self.medals_earned = []
        self.total_earned_amount = 0

    def get_fullname(self):
        return (f"{self.first_name.title()} {self.last_name.title()}")

# A medals class which has the attributes medal_count, medal_type (Either Gold, Silver, Bronze), and medal_value
# When the medals object is created, the constructor should receive the medal attributes as parameters and assign it to the associated attributes
# Each time you create medal object you should store it to the athlete medals list
# Youshould also calculate the total worth of the medals and store it to the Athlete object total_earned_amount attribute
# I want you to store the athletes in a list as you get the information from the keyboard

class Medal:
    def __init__(self, medal_count, medal_type, medal_value, athlete):
        self.medal_count = medal_count
        self.medal_type = medal_type
        self.medal_value = medal_value
        athlete.medals_earned.append(self)
        athlete.total_earned_amount += self.medal_count * self.medal_value


# Prompt the user for the number of athletes to enter
# example output: "Enter Athlete 2's first name: "
# Gold medals are worth 37500 each, Silver medals are worth 22500 each, and Bronze medals are worth 15500 each
athletes = []
num_athletes = int(input("Enter the number of athletes to enter: "))

# Get the data for each athlete one at a time by getting the first and last name and storing the information to an athlete object
# Then load the athlete object into the list (display in the prompt the athlete number starting at #1)
# Then get the number of gold, silver, and bronze medals and store those also to the athlete object
# For each type of medal you will create a medal object and store it to the athlete’s medal list


for i in range(num_athletes):
    first_name = input(f"Enter Athlete {i + 1}'s first name: ")
    last_name = input(f"Enter Athlete {i + 1}'s last name: ")
    athlete = Athlete(first_name, last_name)
    athletes.append(athlete)

    gold_medals = int(input(f"Enter {first_name}'s gold medal count: "))
    silver_medals = int(input(f"Enter {first_name}'s silver medal count: "))
    bronze_medals = int(input(f"Enter {first_name}'s bronze medal count: "))

    Medal(gold_medals, "Gold", 37500, athlete)
    Medal(silver_medals, "Silver", 22500, athlete)
    Medal(bronze_medals, "Bronze", 15500, athlete)


# Calculate the total dollar amount and store it to the medal object and the athlete object
# Gold medals are worth 37500 each, Silver medals are worth 22500 each, and Bronze medals are worth 15500 each
# The monetary amount is calculated by multiplying the number of medals by the amount earned
# For example, if the number of gold medals were 10, the calculated amount would be 10 * 37500 = 375000
# Then repeat this process for each of the athletes, and there is no display or printing information until all the data has been entered for all the athletes
# Write this program

print("\nAthlete Medal Summary")

for athlete in athletes:
    print(f"\nAthlete ID: {athlete.athlete_id}")
    print(f"Name: {athlete.get_fullname()}")

    for medal in athlete.medals_earned:
        value = medal.medal_count * medal.medal_value
        print(f"{medal.medal_type} Medals: {medal.medal_count} (Worth ${value:,.0f})")

    print(f"Total Earned Amount: ${athlete.total_earned_amount:,.0f}")



def get_integer(prompt):
    while True:
        try:
            value = int(input(prompt))
            return value
        except ValueError:
            print("Invalid input. Please enter an integer.")



def format_money(amount):
    return float(f"{amount:.2f}")

# format_money(10)        -> 10.00
# format_money(15.5)      -> 15.50
# format_money(375000)    -> 375000.00